version: "3"
services:
  mysql:
    container_name: stock-list-spring_mysql_1
    build:
      context: ./mysql
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/settings:/etc/mysql/conf.d/
      - ./mysql/data/:/var/lib/mysql/
    environment:
      MYSQL_DATABASE: stock_list
      MYSQL_ROOT_PASSWORD: password
    networks:
      - app-net

  spring-boot:
    build:
      context: ./StockList
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    #restart: always
    depends_on:
      mysql:
        condition: service_started
    entrypoint: "java -jar /app/app.jar"
    networks:
      - app-net
networks:
  app-net:
    driver: bridge
